submap = cursor

bind = , f, exec, mouse-mode point

binde = , m, exec, ydotool mousemove -- -20 0
binde = , n, exec, ydotool mousemove -- 0 20
binde = , e, exec, ydotool mousemove -- 0 -20
binde = , i, exec, ydotool mousemove -- 20 0

binde = ALT, m, exec, ydotool mousemove -- -5 0
binde = ALT, n, exec, ydotool mousemove -- 0 5
binde = ALT, e, exec, ydotool mousemove -- 0 -5
binde = ALT, i, exec, ydotool mousemove -- 5 0

bind =   , t, exec, ydotool click 0x40
bindrt = , t, exec, ydotool click 0x80
bind =   , p, exec, ydotool click 0x40
bindrt = , p, exec, ydotool click 0x80
bind =   , space, exec, ydotool click 0x40
bindrt = , space, exec, ydotool click 0x80
bind =   , r, exec, ydotool click 0x41
bindrt = , r, exec, ydotool click 0x81
bind =   , s, exec, ydotool click 0x42
bindrt = , s, exec, ydotool click 0x82

binde = , d, exec, ydotool mousemove -w -- 0 -1
binde = , u, exec, ydotool mousemove -w -- 0 1
binde = , k, exec, ydotool mousemove -w -- 1 0
binde = , b, exec, ydotool mousemove -w -- -1 0

bindn = , escape, exec, mouse-mode stop
bind = , insert, exec, mouse-mode stop
bind = , t, exec, mouse-mode stop
bind = , space, exec, mouse-mode stop
bind = , r, exec, mouse-mode stop
bind = , s, exec, mouse-mode stop

submap = reset
