bindlu = , switch:on:Lid Switch, exec, lockscreen
bindlu = , switch:on:Lid Switch, exec, systemctl suspend

# top row
bindleu = , XF86AudioRaiseVolume, exec, set-volume up
bindleu = , XF86AudioLowerVolume, exec, set-volume down
bindleu = , XF86AudioMute, exec, set-volume mute

bindleu = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindleu = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bindleu = , XF86KbdBrightnessUp, exec, brightnessctl --device='chromeos::kbd_backlight' set 10%+
bindleu = , XF86KbdBrightnessDown, exec, brightnessctl --device='chromeos::kbd_backlight' set 10%-

bindlu = , XF86AudioPlayPause, exec, playerctl play-pause
bindlu = , XF86AudioNext, exec, playerctl next
bindlu = , XF86AudioPrev, exec, playerctl previous

bindu = , XF86FullScreen, fullscreen, 0
bindu = , XF86Print, fullscreen, 0

bindlu = , Print, exec, hyprshot -m region
bindlu = , Print, exec, mouse-mode start
bindlu = CTRL, Print, exec, hyprshot -m window -m active
bindlu = CTRL SHIFT, Print, exec, hyprshot -m output -m active

bindu = SUPER ALT, g, exec, hyprshade toggle grayscale

# bind = SUPER, space, exec, kb-switcher timed
bindu = , iso_next_group, exec, kb-switcher timed
bindu = SUPER, period, exec, rofimoji
bindu = SUPER, period, exec, window-mode insert
bindu = SUPER, v, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bindu = SUPER, v, exec, window-mode insert
