# reading
from:newsletter.newyorker.com = +reading
from:jacobin.com = +reading
from:substack.com = +reading
from:letterboxd.com = +reading

# announcements
to:hse_formlab = +announcements
to:khanty_exp = +announcements
subject:seminaire_ilfc = +announcements
from:linguistlist.org = +announcements
from:mosling@googlegroups.com = +announcements
from:asav@hse.ru = +announcements
from:V-NYI = +announcements
from:Ling alert = +announcements

# personal -- everything else
(NOT tag:reading) AND (NOT tag:announcements) = +personal

