# vim:ft=kitty

background   {{bg}}
foreground   {{fg}}
selection_background {{fg}}
selection_foreground {{bg}}
url_color    {{accent}}

color0   {{bg}}
color8   {{bg2}}

color1   {{red}}
color9   {{red2}}

color2   {{green}}
color10  {{green2}}

color3   {{yellow}}
color11  {{yellow2}}

color4   {{blue}}
color12  {{blue2}}

color5   {{magenta}}
color13  {{magenta2}}

color6   {{cyan}}
color14  {{cyan2}}

color7   {{fg}}
color15  {{fg2}}
