[ui.anchors]
bottom = true
left = true
right = true
top = true

[ui.window]
h_align = "fill"
v_align = "fill"

[ui.window.box]
h_align = "center"
v_align = "center"
width = 800
height = 600

[ui.window.box.bar]
orientation = "horizontal"
position = "end"

[ui.window.box.bar.entry]
h_align = "fill"
h_expand = true

[ui.window.box.bar.entry.icon]
h_align = "center"
h_expand = true
pixel_size = 24
theme = nan

[ui.window.box.ai_scroll]
name = "aiScroll"
h_align = "fill"
v_align = "fill"
max_height = 300
min_width = 400
height = 300
width = 400

[ui.window.box.ai_scroll.margins]
top = 8

[ui.window.box.ai_scroll.list]
name = "aiList"
orientation = "vertical"
width = 400
spacing = 10

[ui.window.box.ai_scroll.list.item]
name = "aiItem"
h_align = "fill"
v_align = "fill"
x_align = 0
y_align = 0
wrap = true

[ui.window.box.scroll.list]
max_height = 480

[ui.window.box.scroll.list.item.activation_label]
h_align = "fill"
v_align = "fill"
width = 20
x_align = 0.5
y_align = 0.5

[ui.window.box.scroll.list.item]
height = 25

[ui.window.box.scroll.list.item.icon]
hide = true
pixel_size = 26
theme = ""

[ui.window.box.scroll.list.margins]
top = 20

[ui.window.box.search.prompt]
name = "prompt"
text = "search"

[ui.window.box.search.input]
h_align = "fill"
h_expand = true
icons = false

[ui.window.box.search.spinner]
hide = true
