inherits = "base16_transparent"

"ui.statusline" = "{{accent-name}}"
"ui.background" = "{{accent-name}}"
"ui.background.separator" = "{{accent-name}}"
"ui.popup" = {"fg" = "{{accent-name}}", "bg" = "{{bg}}"}
"ui.menu" = {"fg" = "white", "bg" = "{{bg-off}}"}
"ui.help" = "red"
"ui.window" = "red"

"comment" = { modifiers = ["italic"], fg = "{{gray}}" }
