#!/usr/bin/zsh

if [[ $1 == "s" ]]; then
	WTTR=$(curl -s "wttr.in/@1.1.1.1?format=%t,%C")
	TEMP=${WTTR%,*}
	COND=$(echo ${WTTR#*,} | tr '[:upper:]' '[:lower:]' | xargs)
	echo "$TEMP and $COND"
else
	kitty --class popup-weather sh -c 'curl -s "wttr.in/?T" | less'
fi
