#!/usr/bin/bash

if [[ $1 == "s" ]]; then
	cur=$(wego --frontend=json | jq -r '.Current')
	if [ -n "$cur" ]; then
		temp=$(echo $cur | jq -r '.TempC')
		desc=$(echo $cur | jq -r '.Desc')
		echo "${temp}°C and $desc"
	else
		echo "what is this place?"
	fi
else
	kitty --class popup-weather --title weather sh -c 'wego | less'
fi
