#!/usr/bin/bash
set -m

function wait-to-close {
  if [[ ${1:0:10} = "openwindow" ]] && [[ $1 == *"qutebrowser"* ]]; then
    echo "exiting"
    kitten @ --password="close" close-window
  fi
}

qutebrowser "$*" & disown
socat -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - | while read -r line; do wait-to-close "$line"; done
