#!/usr/bin/env sh

if [[ $1 == "start" ]]; then
  hyprctl keyword cursor:inactive_timeout 0
  hyprctl keyword cursor:hide_on_key_press false
  window-mode cursor
elif [[ $1 == "stop" ]]; then
  hyprctl keyword cursor:inactive_timeout 3
  hyprctl keyword cursor:hide_on_key_press true
  window-mode prev
elif [[ $1 == "point" ]]; then
  hyprctl dispatch submap insert && wl-kbptr -o modes=floating && window-mode cursor
elif [[ $1 == "point-click" ]]; then
  wl-kbptr -o modes=floating,click
fi
