#!/usr/bin/zsh

if [[ $1 == "start" ]]; then
  hyprctl keyword cursor:inactive_timeout 0
  hyprctl keyword cursor:hide_on_key_press false
  window-mode cursor
elif [[ $1 == "stop" ]]
 then
  hyprctl keyword cursor:inactive_timeout 3
  hyprctl keyword cursor:hide_on_key_press true
  window-mode prev
elif [[ $1 == "point" ]]
 then
  hyprctl dispatch submap insert && wl-kbptr -c ~/.config/wl-kbptr/config && window-mode cursor
fi
