#!/usr/bin/zsh

if [[ $1 == "start" ]]; then
  hyprctl keyword cursor:inactive_timeout 0; hyprctl keyword cursor:hide_on_key_press false; hyprctl dispatch submap cursor
elif [[ $1 == "stop" ]]; then
  hyprctl keyword cursor:inactive_timeout 3; hyprctl keyword cursor:hide_on_key_press true; hyprctl dispatch submap reset 
elif [[ $1 == "point" ]]; then
  hyprctl keyword cursor:inactive_timeout 3; hyprctl dispatch submap reset && wl-kbptr -c ~/.config/wl-kbptr/config
fi
