#!/usr/bin/env bash

function handle {
  if [[ ${1:0:12} == "activewindow" ]]; then
    echo $1
  fi
}

socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
