#! /usr/bin/zsh

BAT=$(echo /sys/class/power_supply/BAT*)
BAT_STATUS="$BAT/status"
BAT_CAP="$BAT/capacity"
LOW_BAT_PERCENT=20

AC_PROFILE="performance"
BAT_PROFILE="balanced"
LOW_BAT_PROFILE="power-saver"

# start the monitor loop
prev=0

while true; do
	# read the current state
	if [[ $(cat "$BAT_STATUS") == "Discharging" ]]; then
		if [[ $(cat "$BAT_CAP") -gt $LOW_BAT_PERCENT ]]; then
			profile=$BAT_PROFILE
		else
			profile=$LOW_BAT_PROFILE
		fi
	else
		profile=$AC_PROFILE
	fi

	# set the new profile
	if [[ $prev != "$profile" ]]; then
		if [[ $profile == $LOW_BAT_PROFILE ]]; then
			notify-send -h string:dunst-stack-tag:batt "low battery" "the battery is $(cat $BAT_CAP)%" --urgency critical
		fi
		if [[ $profile == $AC_PROFILE ]]; then
			notify-send -h string:dunst-stack-tag:batt "charging" "the battery is $(cat $BAT_CAP)% and charging" --urgency critical -t 2000 
		fi
		echo setting power profile to $profile
		powerprofilesctl set $profile
	fi

	prev=$profile

	# wait for the next power change event
	inotifywait -qq "$BAT_STATUS" "$BAT_CAP"
done
