#!/usr/bin/zsh

HISTORY_FILE="$HOME/.koob_ips"

save_addr() {
    local input="$1"

    # Save the string to the history file if not already present
    if ! grep -Fxq "$input" "$HISTORY_FILE"; then
        echo "$input" >> "$HISTORY_FILE"
    fi
}

if [[ -z "$1" ]]; then
    echo "no address passed"
    exit 1
fi

# Call the function with the input string
save_addr "$1"
addr=$1

declare -a dirs=("articles" "books")

for d in "${dirs[@]}"
do
    echo cloning "$d" to "$addr"
    rclone sync $d koob:/mnt/onboard/$d --sftp-host $addr --exclude "*.sdr/**" --exclude ".git/**" --no-update-modtime --verbose
done
