#!/usr/bin/env bash

if [[ $1 == "prev" ]] && [[ -f /tmp/prev-submap ]]; then
  submap=$(< /tmp/prev-submap)
  if [[ $submap == "default" ]]; then
    submap="reset"
  fi
else
  submap=$1
fi


hyprctl submap | head -1 > /tmp/prev-submap

declare -A bordercolors
bordercolors=(
  move     "rgb(4695bd)"
  resize   "rgb(46bd80)"
  launch   "rgb(944540)"
  insert   "rgb(2b2b2b)"
  cursor   "rgb(00000000)"
  reset    "rgb(bd4e46)"
)

bordercolor=${bordercolors[$submap]}

hyprctl dispatch submap $submap

hyprctl keyword group:groupbar:col.locked_active $bordercolor
hyprctl keyword group:groupbar:col.active $bordercolor
hyprctl keyword general:col.active_border $bordercolor
hyprctl keyword group:col.border_active $bordercolor

# make new windows open in group when in insert mode
# outside otherwise
# if [[ $submap == "insert" ]]; then
#   hyprctl keyword group:auto_group true
# else
#   hyprctl keyword group:auto_group false
# fi
  
