[symlinks]
"bottom.toml" = "/home/ark/.config/bottom/bottom.toml"
"clipse/config.json" = "/home/ark/.config/clipse/config.json"
"clipse/custom_theme.json" = "/home/ark/.config/clipse/custom_theme.json"
dunstrc = "/home/ark/.config/dunst/dunstrc"
"hypr/hyprland.conf" = "/home/ark/.config/hypr/hyprland.conf"
"hypr/hyprlock.conf" = "/home/ark/.config/hypr/hyprlock.conf"
"hypr/hyprpaper.conf" = "/home/ark/.config/hypr/hyprpaper.conf"
"hypr/keybindings.conf" = "/home/ark/.config/hypr/keybindings.conf"
"hypr/plugins.conf" = "/home/ark/.config/hypr/plugins.conf"
"hypr/theme.conf" = "/home/ark/.config/hypr/theme.conf"
"hypr/windows.conf" = "/home/ark/.config/hypr/windows.conf"
"kitty/current-theme.conf" = "/home/ark/.config/kitty/current-theme.conf"
"kitty/kitty.conf" = "/home/ark/.config/kitty/kitty.conf"
"kitty/kitty.conf.bak" = "/home/ark/.config/kitty/kitty.conf.bak"
"popups/bt" = "/home/ark/bin/bt"
"popups/calendar" = "/home/ark/bin/calendar"
"popups/sysmonitor" = "/home/ark/bin/sysmonitor"
"popups/weather" = "/home/ark/bin/weather"
"popups/wifi" = "/home/ark/bin/wifi"
"rofi/config.rasi" = "/home/ark/.config/rofi/config.rasi"
"rofi/theme.rasi" = "/home/ark/.config/rofi/themes/concrete.rasi"
"scripts/kb-switcher" = "/home/ark/bin/kb-switcher"
"scripts/minecraft" = "/home/ark/bin/minecraft"
"scripts/popup-killer" = "/home/ark/bin/popup-killer"
"scripts/power-mode-switcher" = "/home/ark/bin/power-mode-switcher"
"scripts/rclone-gdrive" = "/home/ark/bin/rclone-gdrive"
"scripts/rclone-koob" = "/home/ark/bin/rclone-koob"
"systemd/calcurse-caldav.service" = "/home/ark/.config/systemd/user/calcurse-caldav.service"
"systemd/calcurse-caldav.timer" = "/home/ark/.config/systemd/user/calcurse-caldav.timer"
"systemd/docker.service" = "/home/ark/.config/systemd/user/docker.service"
"systemd/popup-killer.service" = "/home/ark/.config/systemd/user/popup-killer.service"
"systemd/power-mode-switcher.service" = "/home/ark/.config/systemd/user/power-mode-switcher.service"
"systemd/rclone-gdrive.service" = "/home/ark/.config/systemd/user/rclone-gdrive.service"
"systemd/rclone-gdrive.timer" = "/home/ark/.config/systemd/user/rclone-gdrive.timer"
"v2raya.json" = "/home/ark/.config/v2raya/current-config.json"
"waybar/config.jsonc" = "/home/ark/.config/waybar/config.jsonc"
"waybar/style.css" = "/home/ark/.config/waybar/style.css"

[templates]
