[default.files]
"helix" = "~/.config/helix"
"lesskey" = "~/.config/lesskey"
"bottom.toml" = "~/.config/bottom/bottom.toml"
"dunstrc" = "~/.config/dunst/dunstrc"
"hypr" = "~/.config/hypr"
"kitty" = "~/.config/kitty"
"qutebrowser/config.py" = "~/.config/qutebrowser/config.py"
"qutebrowser/colors.py" = "~/.config/qutebrowser/colors.py"
"sioyek" = "~/.config/sioyek"
"papis" = { target = "~/.config/papis", type = "symbolic" }
"notmuch" = "~/.config/notmuch"
"himalaya" = "~/.config/himalaya"
"wl-kbptr" = "~/.config/wl-kbptr"
"rofi" = "~/.config/rofi"
"rofimoji.rc" = "~/.config/rofimoji.rc"
"rofi-rbw.rc" = "~/.config/rofi-rbw.rc"
"waybar" = "~/.config/waybar"
"wob" = "~/.config/wob"
"systemd" = "~/.config/systemd/user"
"v2raya.json" = "~/.config/v2raya/current-config.json"
"tridactyl" = "~/.config/tridactyl"
"scripts" = "~/.local/bin"
"popups" = "~/.local/bin"
"kmonad" = "/etc/kmonad"
"logind.conf" = "/etc/systemd/logind.conf"
"ly/config.ini" = "/etc/ly/config.ini"
"fish" = "~/.config/fish"
"mimeapps.list" = "~/.config/mimeapps.list"
"applications" = "~/.local/share/applications/usr"

[helpers]
rgb = ".dotter/rgb.rhai"
drop-first = ".dotter/drop-first.rhai"

[default.variables]
bg = "#ffffff"
red = "#bd4e46"
green = "#46bd80"
yellow = "#b3a430"
blue = "#4695bd"
magenta = "#a64eb5"
cyan = "#46b5bd"
fg = "#000000"

bg2 = "#b7b7b7"
red2 = "#944540"
green2 = "#409168"
yellow2 = "#9e9336"
blue2 = "#45748c"
magenta2 = "#814c8a"
cyan2 = "#428085"
fg2 = "#0b0b0b"

accent-name = "red"
accent = "#bd4e46"
accent2 = "#944540"

gray = "#909090"
bg-off = "#fafafa"
